// Package docs GENERATED BY THE COMMAND ABOVE; DO NOT EDIT
// This file was generated by swaggo/swag
package docs

import (
	"bytes"
	"encoding/json"
	"strings"
	"text/template"

	"github.com/swaggo/swag"
)

var doc = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "https://swagger.io/terms/",
        "contact": {
            "name": "Team Georepublic",
            "email": "info@georepublic.de"
        },
        "license": {
            "name": "GNU Affero General Public License",
            "url": "https://www.gnu.org/licenses/agpl-3.0.en.html"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/breaks/{break_id}": {
            "get": {
                "description": "Fetch a break with its break_id",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Break"
                ],
                "summary": "Fetch a break",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Break ID",
                        "name": "break_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/database.Break"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/util.MultiError"
                        }
                    }
                }
            },
            "delete": {
                "description": "Delete a break with its break_id",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Break"
                ],
                "summary": "Delete a break",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Break ID",
                        "name": "break_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/util.Success"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/util.MultiError"
                        }
                    }
                }
            },
            "patch": {
                "description": "Update a break with its break_id",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Break"
                ],
                "summary": "Update a break",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Break ID",
                        "name": "break_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Update break",
                        "name": "Break",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/database.CreateBreakParams"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/database.Break"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/util.MultiError"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/util.NotFound"
                        }
                    }
                }
            }
        },
        "/breaks/{break_id}/time_windows": {
            "get": {
                "description": "Get a list of break time windows for a break with break_id",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Break"
                ],
                "summary": "List break time windows for a break",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Break ID",
                        "name": "break_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/database.BreakTimeWindow"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/util.MultiError"
                        }
                    }
                }
            },
            "post": {
                "description": "Create a new break time window with the input payload",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Break"
                ],
                "summary": "Create a new break time window",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Break ID",
                        "name": "break_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Create break time window",
                        "name": "BreakTimeWindow",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/database.CreateBreakTimeWindowParams"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/database.BreakTimeWindow"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/util.MultiError"
                        }
                    }
                }
            }
        },
        "/breaks/{break_id}/time_windows/{tw_open}/{tw_close}": {
            "delete": {
                "description": "Delete break time windows for a break with break_id",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Break"
                ],
                "summary": "Delete break time windows",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Break ID",
                        "name": "break_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Break opening Time Window",
                        "name": "tw_open",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Break closing Time Window",
                        "name": "tw_close",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/util.Success"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/util.MultiError"
                        }
                    }
                }
            }
        },
        "/jobs/{job_id}": {
            "get": {
                "description": "Fetch a job with its job_id",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Job"
                ],
                "summary": "Fetch a job",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Job ID",
                        "name": "job_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/database.Job"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/util.MultiError"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/util.NotFound"
                        }
                    }
                }
            },
            "delete": {
                "description": "Delete a job with its job_id",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Job"
                ],
                "summary": "Delete a job",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Job ID",
                        "name": "job_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/util.Success"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/util.MultiError"
                        }
                    }
                }
            },
            "patch": {
                "description": "Update a job (partial update) with its job_id",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Job"
                ],
                "summary": "Update a job",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Job ID",
                        "name": "job_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/database.Job"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/util.MultiError"
                        }
                    }
                }
            }
        },
        "/jobs/{job_id}/time_windows": {
            "get": {
                "description": "Get a list of job time windows for a job with job_id",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Job"
                ],
                "summary": "List job time windows for a job",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Job ID",
                        "name": "job_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/database.JobTimeWindow"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/util.MultiError"
                        }
                    }
                }
            },
            "post": {
                "description": "Create a new job time window with the input payload",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Job"
                ],
                "summary": "Create a new job time window",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Job ID",
                        "name": "job_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Create job time window",
                        "name": "JobTimeWindow",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/database.CreateJobTimeWindowParams"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/database.JobTimeWindow"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/util.MultiError"
                        }
                    }
                }
            }
        },
        "/jobs/{job_id}/time_windows/{tw_open}/{tw_close}": {
            "delete": {
                "description": "Delete job time windows for a job with job_id",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Job"
                ],
                "summary": "Delete job time windows",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Job ID",
                        "name": "job_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Job opening Time Window",
                        "name": "tw_open",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Job closing Time Window",
                        "name": "tw_close",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/util.Success"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/util.MultiError"
                        }
                    }
                }
            }
        },
        "/projects": {
            "get": {
                "description": "Get a list of projects",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Project"
                ],
                "summary": "List projects",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/database.Project"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/util.MultiError"
                        }
                    }
                }
            },
            "post": {
                "description": "Create a new project with the input payload",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Project"
                ],
                "summary": "Create a new project",
                "parameters": [
                    {
                        "description": "Create project",
                        "name": "Project",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/database.CreateProjectParams"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/database.Project"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/util.MultiError"
                        }
                    }
                }
            }
        },
        "/projects/{project_id}": {
            "get": {
                "description": "Fetch a project with its project_id",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Project"
                ],
                "summary": "Fetch a project",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Project ID",
                        "name": "project_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/database.Project"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/util.MultiError"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/util.NotFound"
                        }
                    }
                }
            },
            "delete": {
                "description": "Delete a project with its project_id",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Project"
                ],
                "summary": "Delete a project",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Project ID",
                        "name": "project_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/util.Success"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/util.MultiError"
                        }
                    }
                }
            },
            "patch": {
                "description": "Update a project with its project_id",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Project"
                ],
                "summary": "Update a project",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Project ID",
                        "name": "project_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Update project",
                        "name": "Project",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/database.CreateProjectParams"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/database.Project"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/util.MultiError"
                        }
                    }
                }
            }
        },
        "/projects/{project_id}/jobs": {
            "get": {
                "description": "Get a list of jobs for a project with project_id",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Job"
                ],
                "summary": "List jobs for a project",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Project ID",
                        "name": "project_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/database.Job"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/util.MultiError"
                        }
                    }
                }
            },
            "post": {
                "description": "Create a new job with the input payload",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Job"
                ],
                "summary": "Create a new job",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Project ID",
                        "name": "project_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Job object",
                        "name": "Job",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/database.CreateJobParams"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/database.Job"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/util.MultiError"
                        }
                    }
                }
            }
        },
        "/projects/{project_id}/schedule": {
            "get": {
                "description": "Get the schedule for a project",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "text/calendar"
                ],
                "tags": [
                    "Schedule"
                ],
                "summary": "Get the schedule",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Project ID",
                        "name": "project_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/util.Schedule"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/util.MultiError"
                        }
                    }
                }
            },
            "post": {
                "description": "Schedule the tasks present in a project",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Schedule"
                ],
                "summary": "Schedule the tasks",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Project ID",
                        "name": "project_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/util.Schedule"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/util.MultiError"
                        }
                    }
                }
            },
            "delete": {
                "description": "Delete the schedule for a project",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Schedule"
                ],
                "summary": "Delete the schedule",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Project ID",
                        "name": "project_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/util.Success"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/util.MultiError"
                        }
                    }
                }
            }
        },
        "/projects/{project_id}/shipments": {
            "get": {
                "description": "Get a list of shipments for a project with project_id",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Shipment"
                ],
                "summary": "List shipments for a project",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Project ID",
                        "name": "project_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/database.Shipment"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/util.MultiError"
                        }
                    }
                }
            },
            "post": {
                "description": "Create a new shipment with the input payload",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Shipment"
                ],
                "summary": "Create a new shipment",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Project ID",
                        "name": "project_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Create shipment",
                        "name": "Shipment",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/database.CreateShipmentParams"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/database.Shipment"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/util.MultiError"
                        }
                    }
                }
            }
        },
        "/projects/{project_id}/vehicles": {
            "get": {
                "description": "Get a list of vehicles for a project with project_id",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Vehicle"
                ],
                "summary": "List vehicles for a project",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Project ID",
                        "name": "project_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/database.Vehicle"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/util.MultiError"
                        }
                    }
                }
            },
            "post": {
                "description": "Create a new vehicle with the input payload",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Vehicle"
                ],
                "summary": "Create a new vehicle",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Project ID",
                        "name": "project_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Create vehicle",
                        "name": "Vehicle",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/database.CreateVehicleParams"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/database.Vehicle"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/util.MultiError"
                        }
                    }
                }
            }
        },
        "/shipments/{shipment_id}": {
            "get": {
                "description": "Fetch a shipment with its shipment_id",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Shipment"
                ],
                "summary": "Fetch a shipment",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Shipment ID",
                        "name": "shipment_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/database.Shipment"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/util.MultiError"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/util.NotFound"
                        }
                    }
                }
            },
            "delete": {
                "description": "Delete a shipment with its shipment_id",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Shipment"
                ],
                "summary": "Delete a shipment",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Shipment ID",
                        "name": "shipment_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/util.Success"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/util.MultiError"
                        }
                    }
                }
            },
            "patch": {
                "description": "Update a shipment with its shipment_id",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Shipment"
                ],
                "summary": "Update a shipment",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Shipment ID",
                        "name": "shipment_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Update shipment",
                        "name": "Shipment",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/database.UpdateShipmentParams"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/database.Shipment"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/util.MultiError"
                        }
                    }
                }
            }
        },
        "/shipments/{shipment_id}/time_windows": {
            "get": {
                "description": "Get a list of shipment time windows for a shipment with shipment_id",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Shipment"
                ],
                "summary": "List shipment time windows for a shipment",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Shipment ID",
                        "name": "shipment_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/database.ShipmentTimeWindow"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/util.MultiError"
                        }
                    }
                }
            },
            "post": {
                "description": "Create a new shipment time window with the input payload",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Shipment"
                ],
                "summary": "Create a new shipment time window",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Shipment ID",
                        "name": "shipment_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Create shipment time window",
                        "name": "ShipmentTimeWindow",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/database.CreateShipmentTimeWindowParams"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/database.ShipmentTimeWindow"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/util.MultiError"
                        }
                    }
                }
            }
        },
        "/shipments/{shipment_id}/time_windows/{tw_open}/{tw_close}": {
            "delete": {
                "description": "Delete shipment time windows for a shipment with shipment_id",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Shipment"
                ],
                "summary": "Delete shipment time windows",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Shipment ID",
                        "name": "shipment_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Shipment opening Time Window",
                        "name": "tw_open",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Shipment closing Time Window",
                        "name": "tw_close",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/util.Success"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/util.MultiError"
                        }
                    }
                }
            }
        },
        "/vehicles/{vehicle_id}": {
            "get": {
                "description": "Fetch a vehicle with its vehicle_id",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Vehicle"
                ],
                "summary": "Fetch a vehicle",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Vehicle ID",
                        "name": "vehicle_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/database.Vehicle"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/util.MultiError"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/util.NotFound"
                        }
                    }
                }
            },
            "delete": {
                "description": "Delete a vehicle with its vehicle_id",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Vehicle"
                ],
                "summary": "Delete a vehicle",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Vehicle ID",
                        "name": "vehicle_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/util.Success"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/util.MultiError"
                        }
                    }
                }
            },
            "patch": {
                "description": "Update a vehicle with its vehicle_id",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Vehicle"
                ],
                "summary": "Update a vehicle",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Vehicle ID",
                        "name": "vehicle_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Update vehicle",
                        "name": "Vehicle",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/database.UpdateVehicleParams"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/database.Vehicle"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/util.MultiError"
                        }
                    }
                }
            }
        },
        "/vehicles/{vehicle_id}/breaks": {
            "get": {
                "description": "Get a list of breaks",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Break"
                ],
                "summary": "List breaks",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Vehicle ID",
                        "name": "vehicle_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/database.Break"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/util.MultiError"
                        }
                    }
                }
            },
            "post": {
                "description": "Create a new break with the input payload",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Break"
                ],
                "summary": "Create a new break",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Vehicle ID",
                        "name": "vehicle_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Create break",
                        "name": "Break",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/database.CreateBreakParams"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/database.Break"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/util.MultiError"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "database.Break": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string",
                    "example": "2021-12-01 13:00:00"
                },
                "data": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "string"
                    },
                    "example": {
                        "key1": "value1",
                        "key2": "value2"
                    }
                },
                "id": {
                    "type": "string",
                    "example": "1234567812345678"
                },
                "service": {
                    "type": "integer",
                    "example": 120
                },
                "updated_at": {
                    "type": "string",
                    "example": "2021-12-01 13:00:00"
                },
                "vehicle_id": {
                    "type": "string",
                    "example": "1234567812345678"
                }
            }
        },
        "database.BreakTimeWindow": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string",
                    "example": "2021-12-01 13:00:00"
                },
                "id": {
                    "type": "string",
                    "example": "1234567812345678"
                },
                "tw_close": {
                    "type": "string",
                    "example": "2021-12-31 23:59:00"
                },
                "tw_open": {
                    "type": "string",
                    "example": "2021-12-31 23:00:00"
                },
                "updated_at": {
                    "type": "string",
                    "example": "2021-12-01 13:00:00"
                }
            }
        },
        "database.CreateBreakParams": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "string"
                    },
                    "example": {
                        "key1": "value1",
                        "key2": "value2"
                    }
                },
                "service": {
                    "type": "integer",
                    "example": 120
                }
            }
        },
        "database.CreateBreakTimeWindowParams": {
            "type": "object",
            "required": [
                "tw_close",
                "tw_open"
            ],
            "properties": {
                "tw_close": {
                    "type": "string",
                    "example": "2021-12-31 23:59:00"
                },
                "tw_open": {
                    "type": "string",
                    "example": "2021-12-31 23:00:00"
                }
            }
        },
        "database.CreateJobParams": {
            "type": "object",
            "required": [
                "location"
            ],
            "properties": {
                "data": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "string"
                    },
                    "example": {
                        "key1": "value1",
                        "key2": "value2"
                    }
                },
                "delivery": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    },
                    "example": [
                        10,
                        20
                    ]
                },
                "location": {
                    "$ref": "#/definitions/util.LocationParams"
                },
                "pickup": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    },
                    "example": [
                        5,
                        15
                    ]
                },
                "priority": {
                    "type": "integer",
                    "example": 10
                },
                "service": {
                    "type": "integer",
                    "example": 120
                },
                "skills": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    },
                    "example": [
                        1,
                        5
                    ]
                }
            }
        },
        "database.CreateJobTimeWindowParams": {
            "type": "object",
            "required": [
                "tw_close",
                "tw_open"
            ],
            "properties": {
                "tw_close": {
                    "type": "string",
                    "example": "2021-12-31 23:59:00"
                },
                "tw_open": {
                    "type": "string",
                    "example": "2021-12-31 23:00:00"
                }
            }
        },
        "database.CreateProjectParams": {
            "type": "object",
            "required": [
                "name"
            ],
            "properties": {
                "data": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "string"
                    },
                    "example": {
                        "key1": "value1",
                        "key2": "value2"
                    }
                },
                "name": {
                    "type": "string",
                    "example": "Sample Project"
                }
            }
        },
        "database.CreateShipmentParams": {
            "type": "object",
            "required": [
                "d_location",
                "p_location"
            ],
            "properties": {
                "amount": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                },
                "d_location": {
                    "$ref": "#/definitions/util.LocationParams"
                },
                "d_service": {
                    "type": "integer"
                },
                "data": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "string"
                    },
                    "example": {
                        "key1": "value1",
                        "key2": "value2"
                    }
                },
                "p_location": {
                    "$ref": "#/definitions/util.LocationParams"
                },
                "p_service": {
                    "type": "integer"
                },
                "priority": {
                    "type": "integer",
                    "example": 10
                },
                "skills": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    },
                    "example": [
                        1,
                        5
                    ]
                }
            }
        },
        "database.CreateShipmentTimeWindowParams": {
            "type": "object",
            "required": [
                "kind",
                "tw_close",
                "tw_open"
            ],
            "properties": {
                "kind": {
                    "type": "string"
                },
                "tw_close": {
                    "type": "string",
                    "example": "2021-12-31 23:59:00"
                },
                "tw_open": {
                    "type": "string",
                    "example": "2021-12-31 23:00:00"
                }
            }
        },
        "database.CreateVehicleParams": {
            "type": "object",
            "required": [
                "end_location",
                "start_location"
            ],
            "properties": {
                "capacity": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                },
                "data": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "string"
                    },
                    "example": {
                        "key1": "value1",
                        "key2": "value2"
                    }
                },
                "end_location": {
                    "$ref": "#/definitions/util.LocationParams"
                },
                "skills": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    },
                    "example": [
                        1,
                        5
                    ]
                },
                "speed_factor": {
                    "type": "number"
                },
                "start_location": {
                    "$ref": "#/definitions/util.LocationParams"
                },
                "tw_close": {
                    "type": "string"
                },
                "tw_open": {
                    "type": "string"
                }
            }
        },
        "database.Job": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string",
                    "example": "2021-12-01 13:00:00"
                },
                "data": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "string"
                    },
                    "example": {
                        "key1": "value1",
                        "key2": "value2"
                    }
                },
                "delivery": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    },
                    "example": [
                        10,
                        20
                    ]
                },
                "id": {
                    "type": "string",
                    "example": "1234567812345678"
                },
                "location": {
                    "$ref": "#/definitions/util.LocationParams"
                },
                "pickup": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    },
                    "example": [
                        5,
                        15
                    ]
                },
                "priority": {
                    "type": "integer",
                    "example": 10
                },
                "project_id": {
                    "type": "string",
                    "example": "1234567812345678"
                },
                "service": {
                    "type": "integer",
                    "example": 120
                },
                "skills": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    },
                    "example": [
                        1,
                        5
                    ]
                },
                "updated_at": {
                    "type": "string",
                    "example": "2021-12-01 13:00:00"
                }
            }
        },
        "database.JobTimeWindow": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string",
                    "example": "2021-12-01 13:00:00"
                },
                "id": {
                    "type": "string",
                    "example": "1234567812345678"
                },
                "tw_close": {
                    "type": "string",
                    "example": "2021-12-31 23:59:00"
                },
                "tw_open": {
                    "type": "string",
                    "example": "2021-12-31 23:00:00"
                },
                "updated_at": {
                    "type": "string",
                    "example": "2021-12-01 13:00:00"
                }
            }
        },
        "database.Project": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string",
                    "example": "2021-12-01 13:00:00"
                },
                "data": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "string"
                    },
                    "example": {
                        "key1": "value1",
                        "key2": "value2"
                    }
                },
                "id": {
                    "type": "string",
                    "example": "1234567812345678"
                },
                "name": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "string",
                    "example": "2021-12-01 13:00:00"
                }
            }
        },
        "database.Shipment": {
            "type": "object",
            "properties": {
                "amount": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                },
                "created_at": {
                    "type": "string",
                    "example": "2021-12-01 13:00:00"
                },
                "d_location": {
                    "$ref": "#/definitions/util.LocationParams"
                },
                "d_service": {
                    "type": "integer"
                },
                "data": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "string"
                    },
                    "example": {
                        "key1": "value1",
                        "key2": "value2"
                    }
                },
                "id": {
                    "type": "string",
                    "example": "1234567812345678"
                },
                "p_location": {
                    "$ref": "#/definitions/util.LocationParams"
                },
                "p_service": {
                    "type": "integer"
                },
                "priority": {
                    "type": "integer",
                    "example": 10
                },
                "project_id": {
                    "type": "string",
                    "example": "1234567812345678"
                },
                "skills": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    },
                    "example": [
                        1,
                        5
                    ]
                },
                "updated_at": {
                    "type": "string",
                    "example": "2021-12-01 13:00:00"
                }
            }
        },
        "database.ShipmentTimeWindow": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string",
                    "example": "2021-12-01 13:00:00"
                },
                "id": {
                    "type": "string",
                    "example": "1234567812345678"
                },
                "kind": {
                    "type": "string"
                },
                "tw_close": {
                    "type": "string",
                    "example": "2021-12-31 23:59:00"
                },
                "tw_open": {
                    "type": "string",
                    "example": "2021-12-31 23:00:00"
                },
                "updated_at": {
                    "type": "string",
                    "example": "2021-12-01 13:00:00"
                }
            }
        },
        "database.UpdateShipmentParams": {
            "type": "object",
            "properties": {
                "amount": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                },
                "d_location": {
                    "$ref": "#/definitions/util.LocationParams"
                },
                "d_service": {
                    "type": "integer"
                },
                "data": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "string"
                    },
                    "example": {
                        "key1": "value1",
                        "key2": "value2"
                    }
                },
                "p_location": {
                    "$ref": "#/definitions/util.LocationParams"
                },
                "p_service": {
                    "type": "integer"
                },
                "priority": {
                    "type": "integer",
                    "example": 10
                },
                "project_id": {
                    "type": "string",
                    "example": "1234567812345678"
                },
                "skills": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    },
                    "example": [
                        1,
                        5
                    ]
                }
            }
        },
        "database.UpdateVehicleParams": {
            "type": "object",
            "properties": {
                "capacity": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                },
                "data": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "string"
                    },
                    "example": {
                        "key1": "value1",
                        "key2": "value2"
                    }
                },
                "end_location": {
                    "$ref": "#/definitions/util.LocationParams"
                },
                "project_id": {
                    "type": "string",
                    "example": "1234567812345678"
                },
                "skills": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    },
                    "example": [
                        1,
                        5
                    ]
                },
                "speed_factor": {
                    "type": "number"
                },
                "start_location": {
                    "$ref": "#/definitions/util.LocationParams"
                },
                "tw_close": {
                    "type": "string"
                },
                "tw_open": {
                    "type": "string"
                }
            }
        },
        "database.Vehicle": {
            "type": "object",
            "properties": {
                "capacity": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                },
                "created_at": {
                    "type": "string",
                    "example": "2021-12-01 13:00:00"
                },
                "data": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "string"
                    },
                    "example": {
                        "key1": "value1",
                        "key2": "value2"
                    }
                },
                "end_location": {
                    "$ref": "#/definitions/util.LocationParams"
                },
                "id": {
                    "type": "string",
                    "example": "1234567812345678"
                },
                "project_id": {
                    "type": "string",
                    "example": "1234567812345678"
                },
                "skills": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    },
                    "example": [
                        1,
                        5
                    ]
                },
                "speed_factor": {
                    "type": "number"
                },
                "start_location": {
                    "$ref": "#/definitions/util.LocationParams"
                },
                "tw_close": {
                    "type": "string",
                    "example": "2021-12-31 23:59:00"
                },
                "tw_open": {
                    "type": "string",
                    "example": "2021-12-31 23:00:00"
                },
                "updated_at": {
                    "type": "string",
                    "example": "2021-12-01 13:00:00"
                }
            }
        },
        "util.LocationParams": {
            "type": "object",
            "required": [
                "latitude",
                "longitude"
            ],
            "properties": {
                "latitude": {
                    "type": "number",
                    "example": 2.0365
                },
                "longitude": {
                    "type": "number",
                    "example": 48.6113
                }
            }
        },
        "util.MultiError": {
            "type": "object",
            "properties": {
                "errors": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    },
                    "example": [
                        "Error message1",
                        "Error message2"
                    ]
                }
            }
        },
        "util.NotFound": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string",
                    "example": "Not Found"
                }
            }
        },
        "util.Schedule": {
            "type": "object",
            "properties": {
                "arrival": {
                    "type": "string"
                },
                "breakID": {
                    "type": "integer"
                },
                "createdAt": {
                    "type": "string"
                },
                "departure": {
                    "type": "string"
                },
                "endLoad": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                },
                "id": {
                    "type": "integer"
                },
                "jobID": {
                    "type": "integer"
                },
                "projectID": {
                    "type": "integer"
                },
                "serviceTime": {
                    "type": "integer"
                },
                "shipmentID": {
                    "type": "integer"
                },
                "startLoad": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                },
                "travelTime": {
                    "type": "integer"
                },
                "type": {
                    "type": "integer"
                },
                "updatedAt": {
                    "type": "string"
                },
                "vehicleID": {
                    "type": "integer"
                },
                "waitingTime": {
                    "type": "integer"
                }
            }
        },
        "util.Success": {
            "type": "object",
            "properties": {
                "success": {
                    "type": "string",
                    "example": "true"
                }
            }
        }
    }
}`

type swaggerInfo struct {
	Version     string
	Host        string
	BasePath    string
	Schemes     []string
	Title       string
	Description string
}

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = swaggerInfo{
	Version:     "0.1.0",
	Host:        "localhost:9100",
	BasePath:    "/",
	Schemes:     []string{"http", "https"},
	Title:       "pg_scheduleserv API",
	Description: "This is an API for scheduling VRP tasks. Source code can be found on https://github.com/Georepublic/pg_scheduleserv",
}

type s struct{}

func (s *s) ReadDoc() string {
	sInfo := SwaggerInfo
	sInfo.Description = strings.Replace(sInfo.Description, "\n", "\\n", -1)

	t, err := template.New("swagger_info").Funcs(template.FuncMap{
		"marshal": func(v interface{}) string {
			a, _ := json.Marshal(v)
			return string(a)
		},
		"escape": func(v interface{}) string {
			// escape tabs
			str := strings.Replace(v.(string), "\t", "\\t", -1)
			// replace " with \", and if that results in \\", replace that with \\\"
			str = strings.Replace(str, "\"", "\\\"", -1)
			return strings.Replace(str, "\\\\\"", "\\\\\\\"", -1)
		},
	}).Parse(doc)
	if err != nil {
		return doc
	}

	var tpl bytes.Buffer
	if err := t.Execute(&tpl, sInfo); err != nil {
		return doc
	}

	return tpl.String()
}

func init() {
	swag.Register(swag.Name, &s{})
}
